"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "../styled-components/registry";
import { GlobalStyles } from "../styles/global";
import { Header } from "../components/Header";
import light from "../styles/theme/light";
import { useState } from "react";
import dark from "../styles/theme/dark";
import { ThemeProvider } from "styled-components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
  const [theme, setTheme] = useState(light);

  const toggledTheme = () => {
    setTheme(theme.title === "light" ? dark : light);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ThemeProvider theme={theme}>
            {children}
            <Header toggleTheme={toggledTheme} />
            <GlobalStyles />
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
