'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "../styled-components/registry";
import { GlobalStyles } from "../styled-components/global";
import { StyledProviderTheme } from "../providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <StyledProviderTheme>
            <GlobalStyles />
            {children}
          </StyledProviderTheme>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
